- name: Install basic utilities
  ansible.builtin.apt:
    name:
      - wget
      - curl
      - vim
      - openssl
      - socat      
      - conntrack 
      - ipset    
      - kmod
      - python3-pip
      - python3-kubernetes
    state: present
    update_cache: true
