- name: Update /etc/hosts with all inventory hosts
  become: yes
  ansible.builtin.import_tasks: hosts.yml
  tags: hosts

- name: Install Default Packages
  become: yes
  ansible.builtin.import_tasks: default_packages.yml
  tags: default_packages
