- name: Ensure Kubeconfig Output Directory Exists
  ansible.builtin.file:
    path: "{{ kubeconfig_directory }}"
    state: directory
    mode: '0755'

- name: Generate Workers Kubeconfigs
  ansible.builtin.template:
    src: kubeconfig.j2
    dest: "{{ kubeconfig_directory }}/{{ item }}.kubeconfig"
    mode: '0600'
  vars:
    server: "{{ worker_k8s_component.kubeconfig_server }}"
    user: "system:node:{{ item }}"
    ca_cert: "{{ lookup('file', pki_directory + '/ca.pem') }}"
    client_cert: "{{ lookup('file', pki_directory + '/' + item + '.pem') }}"
    client_key: "{{ lookup('file', pki_directory + '/' + item + '-key.pem') }}"
  loop: "{{ groups['workers'] }}"

- name: Generate Service Kubeconfigs
  ansible.builtin.template:
    src: kubeconfig.j2
    dest: "{{ kubeconfig_directory }}/{{ item.value.cert_name }}.kubeconfig"
    mode: '0600'
  vars:
    server: "{{ item.value.kubeconfig_server }}"
    user: "{{ item.value.kubeconfig_user }}"
    ca_cert: "{{ lookup('file', pki_directory + '/ca.pem') }}"
    client_cert: "{{ lookup('file', pki_directory + '/' + item.value.cert_name + '.pem') }}"
    client_key: "{{ lookup('file', pki_directory + '/' + item.value.cert_name + '-key.pem') }}"
  loop: "{{ k8s_components | dict2items }}"
  when: item.value.gen_kubeconfig | default(false)
