- name: Create Kubernetes PKI Directory on Controllers
  file:
    path: /var/lib/kubernetes
    state: directory
    mode: '0755'

- name: Distribute Control Plane Certificates
  copy:
    src: "../pki/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
    mode: '0640'
  loop: "{{ certs_to_transfer }}"
