# System users and groups for Kubernetes
system_users:
  - etcd
  - kubernetes

# K8s binaries needed on controller nodes
k8s_binary_list: "{{ k8s_binaries.controller }}"

# PKI Certificates to transfer to controller nodes
certs_to_transfer:
  - "{{ certificate_authorities.kubernetes_ca.name }}"
  - kubernetes-aggregation-layer.pem
  - kubernetes-aggregation-layer-key.pem
  - kube-apiserver.pem
  - kube-apiserver-key.pem
  - service-accounts.pem    
  - service-accounts-key.pem

