---
## ==========================================
## PKI Configuration (Vault)
## ==========================================
vault_addr: "{{ lookup('env', 'VAULT_ADDR') }}"
vault_cacert: "{{ lookup('env', 'VAULT_CACERT') }}"
vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"

# Global defaults
pki_mount: "pki"
cert_ttl: "876h"
