- name: Generate the Aggregation Layer Certificate
  community.hashi_vault.vault_pki_generate_certificate:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ certificate_authorities.kubernetes_aggregation_layer_ca.path }}"
    
    role_name: "{{ aggregation_layer_k8s_component.vault_role }}"
    common_name: "{{ aggregation_layer_k8s_component.cn }}"
    ttl: "{{ cert_ttl }}"
    
    alt_names: "{{ aggregation_layer_k8s_component.cn }}"
  register: pki_output

- name: Save the Aggregation Layer Certificate
  ansible.builtin.copy:
    content: "{{ pki_output.data.data.certificate }}\n{{ pki_output.data.data.issuing_ca }}"
    dest: "{{ pki_directory }}/{{ aggregation_layer_k8s_component.cn }}.pem"
    mode: '0644'

- name: Save the Aggregation Layer Private Key
  ansible.builtin.copy:
    content: "{{ pki_output.data.data.private_key }}"
    dest: "{{ pki_directory }}/{{ aggregation_layer_k8s_component.cn }}-key.pem"
    mode: '0600'
