- name: Generate the Workers Kubernetes Certificates
  community.hashi_vault.vault_pki_generate_certificate:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_point: "{{ pki_mount }}"
    
    role_name: "{{ worker_cert_template.role }}"
    common_name: "system:node:{{ item }}"
    ttl: "{{ cert_ttl }}"
    
    alt_names: ["{{ item }}"]
    ip_sans: 
      - "{{ worker_cert_template.san_ips }}"
      - "{{ hostvars[item]['ansible_host'] }}"

  loop: "{{ groups['workers'] }}"
  loop_control:
    label: "{{ item }}"
  register: worker_pki_output

- name: Generate the rest of the Kubernetes Certificates
  community.hashi_vault.vault_pki_generate_certificate:
    url: "{{ vault_addr }}"
    token: "{{ vault_token }}"
    mount_point: "{{ pki_mount }}"
    
    role_name: "{{ item.value.role }}"
    common_name: "{{ item.value.cn }}"
    ttl: "{{ cert_ttl }}"
    
    alt_names: "{{ item.value.san_dns | default([]) }}"
    ip_sans: "{{ item.value.san_ips | default([]) }}"

  loop: "{{ k8s_certificates | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  register: pki_output

- name: Ensure PKI directory exists
  ansible.builtin.file:
    path: "{{ item.value.dest_dir }}"
    state: directory
    mode: '0755'
  loop: "{{ k8s_certificates | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Save the Workers Certificates to Files
  ansible.builtin.copy:
    content: "{{ item.data.data.certificate }}\n{{ item.data.data.issuing_ca }}"
    dest: "{{ worker_cert_template.dest_dir }}/{{ item.item }}.pem"
    mode: '0644'
  loop: "{{ worker_pki_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Save  the rest of the Certificates to Files
  ansible.builtin.copy:
    content: "{{ item.data.data.certificate }}\n{{ item.data.data.issuing_ca }}"
    dest: "{{ item.item.value.dest_dir }}/{{ item.item.key }}.pem"
    mode: '0644'
  loop: "{{ pki_output.results }}"
  loop_control:
    label: "{{ item.item.key }}"

- name: Save the Workers Private Keys to Files
  ansible.builtin.copy:
    content: "{{ item.data.data.private_key }}"
    dest: "{{ worker_cert_template.dest_dir }}/{{ item.item }}-key.pem"
    mode: '0600'
  loop: "{{ worker_pki_output.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Save the rest of the Private Keys to Files
  ansible.builtin.copy:
    content: "{{ item.data.data.private_key }}"
    dest: "{{ item.item.value.dest_dir }}/{{ item.item.key }}-key.pem"
    mode: '0600'
  loop: "{{ pki_output.results }}"
  loop_control:
    label: "{{ item.item.key }}"
