- name: Ensure PKI directory exists
  ansible.builtin.file:
    path: "{{ pki_directory }}"
    state: directory
    mode: '0755'
  tags: 
    - pull_ca_certificate
    - worker_certificates
    - other_certificates

- name: Pull the CA Certificate from Vault
  ansible.builtin.get_url:
    url: "{{ vault_addr }}/v1/{{ pki_mount }}/ca/pem"
    dest: "{{ pki_directory }}/ca.pem"
    mode: '0644'
    validate_certs: no
  tags: pull_ca_certificate

- name: Generate the Workers Kubernetes Certificates
  ansible.builtin.import_tasks: worker_certificates.yml
  tags: worker_certificates

- name: Generate the rest of the Kubernetes Certificates
  ansible.builtin.import_tasks: other_certificates.yml
  tags: other_certificates
