[gateway]
k8s-gw ansible_host=192.168.1.200

[controllers]
k8s-ctrl-1 ansible_host=10.0.0.1
k8s-ctrl-2 ansible_host=10.0.0.2
k8s-ctrl-3 ansible_host=10.0.0.3

[workers]
k8s-wkr-1 ansible_host=10.0.0.21
k8s-wkr-2 ansible_host=10.0.0.22
k8s-wkr-3 ansible_host=10.0.0.23

[clients]
k8s-gw ansible_host=192.168.1.200

[local]
localhost ansible_connection=local

[k8s_cluster:children]
controllers
workers
