- name: Generate PKI
  hosts: localhost
  roles: [vault_pki]
  tags: 
    - vault_pki
    - local_setup

- name: Generate Kubeconfigs
  hosts: localhost
  roles: [kubeconfigs]
  tags: 
    - kubeconfigs
    - local_setup

- name: Default Firewall Setup (Gateway)
  hosts: gateway
  roles: [default_firewall]
  tags: default_firewall_gateway

- name: Default Firewall Setup (Kubernetes Cluster)
  hosts: k8s_cluster
  roles: [default_firewall]
  tags: default_firewall_k8s

- name: Gateway Setup
  hosts: gateway
  roles: [gateway]
  tags: gateway

- name: Base OS Setup
  hosts: k8s_cluster:gateway
  roles: [common]
  tags: common_setup

- name: Bootstrap Etcd
  hosts: etcd_nodes
  roles: [etcd]
  tags: etcd
