- name: Ensure `.kube` directory exists for admin user
  ansible.builtin.file:
    path: "/home/admin/.kube"
    state: directory
    mode: '0755'
    owner: admin
    group: admin

- name: Distribute Administrator's Kubeconfig file to Gateway
  copy:
    src: "{{ kubeconfig_directory }}/admin.kubeconfig"
    dest: "/home/admin/.kube/config"
    mode: '0640' # The kubeconfig contains sensitive information
    owner: admin
    group: admin
