- name: Create API Server Data Directory
  ansible.builtin.file:
    path: "/var/lib/kubernetes"
    state: directory
    #mode: '0700' # Commented out because no restrictions are provided in the guide

- name: Copy Certificates for the API Server
  ansible.builtin.copy:
    src: "{{ pki_directory }}/{{ item }}"
    dest: "/var/lib/kubernetes/{{ item }}"
  loop: 
    - "{{ certificate_authorities.kubernetes_ca.name }}"
    - "{{ certificate_authorities.kubernetes_aggregation_layer_ca.name }}"
    - kubernetes-aggregation-layer.pem
    - kubernetes-aggregation-layer-key.pem
    - kube-apiserver.pem
    - kube-apiserver-key.pem
    - service-accounts.pem    
    - service-accounts-key.pem

- name: Generate 32-byte Encryption Key for API Server
  ansible.builtin.shell: "head -c 32 /dev/urandom | base64"
  register: raw_encryption_key
  delegate_to: localhost
  become: false
  run_once: true

- name: Distribute Encryption Config to API Server
  ansible.builtin.template:
    src: encryption-config.yaml.j2
    dest: "/var/lib/kubernetes/encryption-config.yaml"
    mode: '0600'
  vars:
    k8s_encryption_key: "{{ raw_encryption_key.stdout }}"

- name: Configure API Server Systemd Service
  ansible.builtin.template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
    mode: '0644'

- name: Enable and Start API Server Service
  ansible.builtin.systemd:
    name: kube-apiserver
    state: started
    enabled: true
    daemon_reload: true

- name: Copy Kubeconfig for admin User to API Server
  ansible.builtin.copy:
    src: "{{ kubeconfig_directory }}/admin.kubeconfig"
    dest: "/var/lib/kubernetes/admin.kubeconfig"
    mode: '0644'

- name: Deploy RBAC Configuration for API Server to Kubelet Communication
  ansible.builtin.template:
    src: kube-apiserver-to-kubelet.yaml.j2
    dest: "/var/lib/kubernetes/kube-apiserver-to-kubelet.yaml"
    mode: '0644'

- name: Apply kube-apiserver-to-kubelet RBAC Configuration
  kubernetes.core.k8s:
    kubeconfig: "/var/lib/kubernetes/admin.kubeconfig"
    src: "/var/lib/kubernetes/kube-apiserver-to-kubelet.yaml"
    state: present
