- name: Setup Kubernetes Control Plane Binaries
  become: true
  tags: install_kubernetes_binaries_controllers
  block:
    - name: Ensure Kubernetes Binary Directory exists
      ansible.builtin.file:
        path: "{{ k8s_download_dest }}/{{ k8s_version }}"
        state: directory
        mode: '0755'
    - name: Install Control Plane Binaries 
      ansible.builtin.include_tasks: 
        file: roles/common/tasks/install_k8s_binary.yml
        apply:
          tags: [install_binaries_workers]
      vars:
        binary_item: "{{ item }}"
      loop: "{{ k8s_binary_list }}"

- name: Configure Kubernetes API Server Service
  become: yes
  ansible.builtin.import_tasks: configure_api_server_service.yml
  tags: configure_api_server_service

- name: Configure Kubernetes Controller Manager Service
  become: yes
  ansible.builtin.import_tasks: configure_controller_manager_service.yml
  tags: configure_controller_manager_service

- name: Configure Kubernetes Scheduler Service
  become: yes
  ansible.builtin.import_tasks: configure_scheduler_service.yml
  tags: configure_scheduler_service
